development:
  client_id: b2b_development
  kafka:
    seed_brokers:
      - kafka://localhost:9092
  consumer:
    group_id: b2b_consumer_group
  producer:
    required_acks: 1
    max_retries: 3
    retry_backoff: 1000
  topics:
    domain_testing:
      name: domain_testing
      partitions: 3
      replication_factor: 1
      retention_ms: 604800000  # 7 days
    domain_testing_dlq:
      name: domain_testing_dlq
      partitions: 1
      replication_factor: 1
      retention_ms: 1209600000  # 14 days
    domain_a_record_testing:
      partitions: 3
      replication_factor: 1
      retention_ms: 604800000
    domain_a_record_testing_dlq:
      partitions: 1
      replication_factor: 1
      retention_ms: 604800000

production:
  client_id: b2b_production
  kafka:
    seed_brokers:
      - <%= ENV['KAFKA_BROKERS'] %>
  consumer:
    group_id: b2b_consumer_group
  producer:
    required_acks: -1
    max_retries: 5
    retry_backoff: 1000
  topics:
    domain_testing:
      name: domain_testing
      partitions: 10
      replication_factor: 3
      retention_ms: 604800000  # 7 days
    domain_testing_dlq:
      name: domain_testing_dlq
      partitions: 3
      replication_factor: 3
      retention_ms: 1209600000  # 14 days
    domain_a_record_testing:
      partitions: 10
      replication_factor: 3
      retention_ms: 604800000
    domain_a_record_testing_dlq:
      partitions: 3
      replication_factor: 3
      retention_ms: 604800000 