# Sidekiq configuration with 5 workers per queue
:concurrency: 5
:timeout: 30
:max_retries: 3
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

# All queues configured with 5 workers each
:queues:
  - [financials, 5]
  - [brreg_migration, 5]
  - [company_financials, 5]
  - [DomainTestingService, 5]
  - [DomainARecordTestingService, 5]
  - [default, 5]
  - [mailers, 5]
  - [active_storage_analysis, 5]
  - [active_storage_purge, 5]

# Rate limiting for external API services
:limits:
  financials: 1
  company_financials: 1
  DomainTestingService: 1
  DomainARecordTestingService: 1