:concurrency: 5
:timeout: 30
:max_retries: 3
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

:queues:
  - [DomainTestingService, 2]
  - [DomainARecordTestingService, 2]
  - [default, 1]

:limits:
  DomainTestingService: 3
  DomainARecordTestingService: 3 