# Sidekiq configuration with 25 total workers (to handle multiple queues concurrently)
:concurrency: 25
:timeout: 30
:max_retries: 3
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

# All queues configured with 5 workers each
:queues:
  - [financials, 5]
  - [brreg_migration, 5]
  - [company_financial_data, 5]
  - [company_web_discovery, 5]
  - [company_linkedin_discovery, 5]
  - [company_employee_discovery, 5]
  - [person_profile_extraction, 5]
  - [person_email_extraction, 5]
  - [person_social_media_extraction, 5]
  - [email_verification, 5]
  - [DomainTestingService, 5]
  - [DomainARecordTestingService, 5]
  - [domain_dns_testing, 5]
  - [domain_mx_testing, 5]
  - [default, 5]
  - [mailers, 5]
  - [active_storage_analysis, 5]
  - [active_storage_purge, 5]

# Rate limiting for external API services
:limits:
  financials: 1
  company_financial_data: 1
  company_web_discovery: 1
  company_linkedin_discovery: 1
  company_employee_discovery: 1
  person_profile_extraction: 1
  person_email_extraction: 1
  person_social_media_extraction: 1
  email_verification: 2
  DomainTestingService: 1
  DomainARecordTestingService: 1
  domain_dns_testing: 1
  domain_mx_testing: 1